name: Build ZMK firmware

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Build
        uses: zmkfirmware/zmk-build-action@main
        with:
          board: nice_nano_v2
          shield: my_keyboard
